### ISSUE TITLE
Issue with gitlab-ci angular package or python example

### ISSUE THREAD

**Issue by devopsdymyr** [PacktPublishing/Mastering-GitLab-12#1]
Good to see you book :)
I recently started working on gitlab with kubernetes cluster deployment.
Currently i have some issue on how i can test and code coverage and build and review and deploy to stage and send to production.

can you send me some example on this with some sample project.

@Joustie

**Comment by Joustie** [comment]
I will add a document to this repo in Chapter11  to highlight the steps. The code to use is already in that directory. The eventmanager project is a ruby on rails based app that can be deployed to a kubernetes  cluster.

**Comment by devopsdymyr** [comment]
Thanks let me check that,if you have some reference for python or angular can you share me

**Comment by shubham763** [comment]
Please reopen the issue if it still exists.
